name: Bionic Debug x64

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install bionic dependencies
        run: sudo ./bldsys/posix_linux_x11/install_bionic_dependencies.sh
      - name: build bionic debug
        run: ./bldsys/posix_linux_x11/build_bionic.sh debug x64
      - name: test bionic debug
        run: ./bldsys/posix_linux_x11/run_test.sh debug x64