name: Catalyst Release (Universal Binary)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Catalyst Release (Universal Binary)
        run: ./bldsys/posix_mach/build.sh release catalyst