name: Android Debug (All APP_ABI) (Build On MacOSX)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Android Dependencies (All APP_ABI) (On MacOSX)
        run: ./bldsys/posix_linux_android/macosx_install_dependencies.sh
      - name: Build Android Debug (All APP_ABI) (On MacOSX)
        run: ./bldsys/posix_linux_android/macosx_build_debug.sh