name: Ubuntu LTS Debug x64

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Ubuntu LTS Dependencies
        run: sudo ./bldsys/posix_linux_x11/install_ubuntu_dependencies.sh x64
      - name: Build Ubuntu LTS Debug
        run: ./bldsys/posix_linux_x11/build.sh debug x64