name: IOS Release (Universal Binary)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Sign Xcode
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64_1: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64_1 }}
          BUILD_PROVISION_PROFILE_BASE64_2: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64_2 }}
          BUILD_PROVISION_PROFILE_BASE64_3: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64_3 }}
          BUILD_PROVISION_PROFILE_BASE64_4: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64_4 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: ./bldsys/posix_mach/xcode_sign.sh
      - name: Build IOS Release (Universal Binary)
        run: ./bldsys/posix_mach/build.sh release ios