name: Android Release (All APP_ABI) (Build On MacOSX)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Android Dependencies (All APP_ABI) (On MacOSX)
        run: ./bldsys/posix_linux_android/install_dependencies_macosx.sh
      - name: Build Android Release (All APP_ABI) (On MacOSX)
        run: ./bldsys/posix_linux_android/build_release_macosx.sh