name: Bionic Release x64

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install bionic dependencies
        run: sudo ./bldsys/posix_linux_x11/install_bionic_dependencies.sh
      - name: build bionic release
        run: ./bldsys/posix_linux_x11/build.sh release bionic x64
      - name: test bionic release
        run: ./bldsys/posix_linux_x11/run_tests.sh release x64