name: Build Win32

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    strategy:
        matrix:
            platform: [x86, x64]
            configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - uses: microsoft/setup-msbuild@v1.1
      - run: msbuild .\bldsys\win32_desktop\PatriotEngine.sln /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}}
