name: Ubuntu LTS Release x86

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install ubuntu lts dependencies
        run: sudo ./bldsys/posix_linux_x11/install_ubuntu_dependencies.sh x86
      - name: build ubuntu lts release
        run: ./bldsys/posix_linux_x11/build.sh release x86
      - name: test ubuntu lts release
        run: ./bldsys/posix_linux_x11/run_tests.sh release x86