name: Android Debug (All APP_ABI) (Build On Ubuntu LTS)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Android Dependencies (All APP_ABI) (On Ubuntu LTS)
        run: ./bldsys/posix_linux_android/linux_install_dependencies.sh
      - name: Build Android Debug (All APP_ABI) (On Ubuntu LTS)
        run: ./bldsys/posix_linux_android/linux_build_debug.sh