name: Build Posix Mach Catalyst

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        configuration: [debug, release]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: ./bldsys/posix_mach/build.sh catalyst ${{matrix.configuration}} 