name: Android Release (All APP_ABI) (Build On Windows)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Android Dependencies (All APP_ABI) (On Windows)
        run: ./bldsys/posix_linux_android/windows_install_dependencies.bat
      - name: Build Android Release (All APP_ABI) (On Windows)
        run: ./bldsys/posix_linux_android/windows_build_release.bat