name: Build Posix Linux Android On Ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [debug, release]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: ./bldsys/posix_linux_android/linux_install_dependencies.sh
      - run: ./bldsys/posix_linux_android/linux_build.sh ${{matrix.configuration}}