name: Ubuntu LTS Glibc Release x86

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: install ubuntu glibc dependencies
        run: sudo ./bldsys/posix_linux_x11/install_ubuntu_glibc_dependencies.sh x86
      - name: build ubuntu glibc release
        run: ./bldsys/posix_linux_x11/build.sh release glibc x86
      - name: test ubuntu glibc release
        run: ./bldsys/posix_linux_x11/run_tests.sh release x86