name: Catalyst Debug (Universal Binary)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Sign Xcode Applications
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: ./bldsys/posix_mach/xcode_sign.sh
      - name: Build Catalyst Debug (Universal Binary)
        run: ./bldsys/posix_mach/build.sh debug catalyst